services:
  traefik:
    volumes:
      - ./jwt_public_key.pem:/app/config/jwt_public_key.pem

  user:
    develop:
      watch:
        - action: rebuild
          path: user
        - action: rebuild
          path: common

  user-grpc:
    develop:
      watch:
        - action: rebuild
          path: user
        - action: rebuild
          path: common

  post:
    develop:
      watch:
        - action: rebuild
          path: post
        - action: rebuild
          path: common

  image:
    volumes:
      - ~/.aws:/root/.aws
    develop:
      watch:
        - action: rebuild
          path: image
        - action: rebuild
          path: common

  image-grpc:
    volumes:
      - ~/.aws:/root/.aws
    develop:
      watch:
        - action: rebuild
          path: image
        - action: rebuild
          path: common

secrets:
  mysql_password:
    file: secrets/mysql_password.txt
  jwt_private_key:
    file: secrets/jwt_private_key.pem
  