services:
  traefik:
    image: traefik:3.2.0
    command:
      - --api.insecure=true  # FIXME
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.file.directory=/app/config/traefik_common
      - --entrypoints.web.address=:80
      - --log.level=DEBUG
      - --accesslog=true
    ports:
      - 80:80
      - 127.0.0.1:8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_common:/app/config/traefik_common

  user:
    build:
      context: .
      dockerfile: user/Dockerfile.http
    depends_on:
      - user_db
    env_file:
      - user/.env
    secrets:
      - mysql_password
      - jwt_secret
    labels:
      traefik.enable: "true"
      traefik.http.services.user.loadbalancer.server.port: 8080

      traefik.http.routers.user.rule: Path(`/api/signup`) || Path(`/api/login`) || PathPrefix(`/api/users`)
      traefik.http.routers.user.middlewares: strip-api-prefix@file
      traefik.http.routers.user.service: user
  
  user_grpc:
    build:
      context: .
      dockerfile: user/Dockerfile.grpc
    depends_on:
      - user_db
    env_file:
      - user/.env
    secrets:
      - mysql_password

  user_db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=user_db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_password
    secrets:
      - mysql_password

  user_db_migrations:
    container_name: user_db_migrations
    image: flyway/flyway
    volumes:
      - ./user/migrations:/flyway/sql
    depends_on:
      - user_db
    entrypoint: ["tail", "-f", "/dev/null"]
    secrets:
      - mysql_password

  post:
    build:
      context: .
      dockerfile: post/Dockerfile
    depends_on:
      - post_db
    env_file:
      - post/.env
    secrets:
      - mysql_password
    labels:
      traefik.enable: "true"
      traefik.http.services.post.loadbalancer.server.port: 8080

      traefik.http.routers.post.rule: PathPrefix(`/api/posts`) || PathPrefix(`/api/comments`) || Path(`/api/feed`)
      traefik.http.routers.post.middlewares: strip-api-prefix@file
      traefik.http.routers.post.service: post

  post_db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=post_db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_password
    secrets:
      - mysql_password

  post_db_migrations:
    container_name: post_db_migrations
    image: flyway/flyway
    volumes:
      - ./post/migrations:/flyway/sql
    depends_on:
      - post_db
    entrypoint: ["tail", "-f", "/dev/null"]
    secrets:
      - mysql_password

  image:
    build:
      context: .
      dockerfile: image/Dockerfile.http
    env_file:
      - image/.env
    labels:
      traefik.enable: "true"
      traefik.http.services.image.loadbalancer.server.port: 8080

      traefik.http.routers.image.rule: PathPrefix(`/api/upload-form`)
      traefik.http.routers.image.middlewares: strip-api-prefix@file
      traefik.http.routers.image.service: image
  
  image_grpc:
    build:
      context: .
      dockerfile: image/Dockerfile.grpc
    env_file:
      - image/.env
