services:
  user:
    build:
      context: .
      dockerfile: user/Dockerfile
    ports:
      - 127.0.0.1:8081:8081
    depends_on:
      - user_db
    env_file:
      - user/.env
    secrets:
      - mysql_password
      - jwt_secret

  user_db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=user_db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_password
    secrets:
      - mysql_password

  user_db_migrations:
    container_name: user_db_migrations
    image: flyway/flyway
    volumes:
      - ./user/migrations:/flyway/sql
    depends_on:
      - user_db
    entrypoint: ["tail", "-f", "/dev/null"]
    secrets:
      - mysql_password

  post:
    build:
      context: .
      dockerfile: post/Dockerfile
    ports:
      - 127.0.0.1:8082:8082
    depends_on:
      - post_db
    env_file:
      - post/.env
    secrets:
      - mysql_password

  post_db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=post_db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_password
    secrets:
      - mysql_password

  post_db_migrations:
    container_name: post_db_migrations
    image: flyway/flyway
    volumes:
      - ./post/migrations:/flyway/sql
    depends_on:
      - post_db
    entrypoint: ["tail", "-f", "/dev/null"]
    secrets:
      - mysql_password

  image:
    build:
      context: .
      dockerfile: image/Dockerfile.http
    ports:
      - 127.0.0.1:8085:8085
    env_file:
      - image/.env
  
  image_grpc:
    build:
      context: .
      dockerfile: image/Dockerfile.grpc
