services:
  user_service:
    develop:
      watch:
        - action: rebuild
          path: user_service
        - action: rebuild
          path: common

  post_service:
    develop:
      watch:
        - action: rebuild
          path: post_service
        - action: rebuild
          path: common

  image_service_grpc:
    develop:
      watch:
        - action: rebuild
          path: image_service
        - action: rebuild
          path: common

secrets:
  mysql_password:
    file: secrets/mysql_password.txt
  jwt_secret:
    file: secrets/jwt_secret.txt