# For most of the Traefik definitions Docker/Swarm provider is used. The file provider contains common definitions used by multiple services (like middleware).

http:
  middlewares:
    strip-api-prefix:
      stripPrefix:
        prefixes: /api

    jwt-auth-remove-header:
      headers:
        customRequestHeaders:
          X-User-Id: ""

    jwt-auth-append-header:
      plugin:
        jwt:
          Alg: RS256
          PayloadFields:
            - sub
            - exp
          Keys:
            - /app/config/jwt_public_key.pem
          JwtHeaders:
            X-User-Id: sub

    jwt-auth:
      chain:
        middlewares:
          - jwt-auth-remove-header
          - jwt-auth-append-header
