name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache-dependency-path: "**/*.sum"
      - name: Install Go dependencies
        run: |
          for service in common user post image; do
            (cd $service && go mod download)
          done
      - name: Install packages for code generation
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install go.uber.org/mock/mockgen@latest
      - name: Install Protoc
        uses: Noelware/setup-protoc@1.1.0
      - name: Generate code
        run: |
          for service in common user post image; do
            (cd $service && go generate ./...)
          done
      - name: Test
        run: |
          for service in user post image; do
            (cd $service && go test ./...)
          done